apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: acceleration-a
  name: acceleration-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acceleration-a
  template:
    metadata:
      labels:
        app: acceleration-a
    spec:
      containers:
      - image: acceleration-a:v0.6
        name: acceleration-a
        env:
        - name: WEB_PORT
          value: "3002"
        imagePullPolicy: Never
        ports:
          - name: liveness-port
            containerPort: 3002
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 2
          periodSeconds: 5
